package com.solmit.java.entidad;
// Generated 25/05/2017 03:35:17 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer idProducto;
	private Categoria categoria;
	private String nombre;
	private String descripcion;
	private Long precio;
	private Integer stock;
	private Integer importancia;
	private String imagen;
	private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);

	public Producto() {
	}

	public Producto(Categoria categoria) {
		this.categoria = categoria;
	}

	public Producto(Categoria categoria, String nombre, String descripcion, Long precio, Integer stock,
			Integer importancia, String imagen, Set<DetallePedido> detallePedidos) {
		this.categoria = categoria;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.precio = precio;
		this.stock = stock;
		this.importancia = importancia;
		this.imagen = imagen;
		this.detallePedidos = detallePedidos;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Long getPrecio() {
		return this.precio;
	}

	public void setPrecio(Long precio) {
		this.precio = precio;
	}

	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	public Integer getImportancia() {
		return this.importancia;
	}

	public void setImportancia(Integer importancia) {
		this.importancia = importancia;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public Set<DetallePedido> getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
		this.detallePedidos = detallePedidos;
	}

}
