package com.solmit.java.entidad;
// Generated 25/05/2017 03:35:17 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private String rolNombre;
	private String descripcion;
	private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);

	public Rol() {
	}

	public Rol(String rolNombre) {
		this.rolNombre = rolNombre;
	}

	public Rol(String rolNombre, String descripcion, Set<UsuarioRol> usuarioRols) {
		this.rolNombre = rolNombre;
		this.descripcion = descripcion;
		this.usuarioRols = usuarioRols;
	}

	public String getRolNombre() {
		return this.rolNombre;
	}

	public void setRolNombre(String rolNombre) {
		this.rolNombre = rolNombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<UsuarioRol> getUsuarioRols() {
		return this.usuarioRols;
	}

	public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
		this.usuarioRols = usuarioRols;
	}

}
