package com.solmit.entidad;
// Generated 25/05/2017 05:38:09 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	private Integer idPedido;
	private Usuario usuario;
	private Date fecha;
	private Character estado;
	private Double total;
	private Set<DetallePedido> detallePedidos = new HashSet<DetallePedido>(0);

	public Pedido() {
	}

	public Pedido(Usuario usuario) {
		this.usuario = usuario;
	}

	public Pedido(Usuario usuario, Date fecha, Character estado, Double total, Set<DetallePedido> detallePedidos) {
		this.usuario = usuario;
		this.fecha = fecha;
		this.estado = estado;
		this.total = total;
		this.detallePedidos = detallePedidos;
	}

	public Integer getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(Integer idPedido) {
		this.idPedido = idPedido;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public Set<DetallePedido> getDetallePedidos() {
		return this.detallePedidos;
	}

	public void setDetallePedidos(Set<DetallePedido> detallePedidos) {
		this.detallePedidos = detallePedidos;
	}

}
