package com.solmit.entidad;
// Generated 25/05/2017 05:38:09 PM by Hibernate Tools 5.2.3.Final

/**
 * UsuarioRol generated by hbm2java
 */
public class UsuarioRol implements java.io.Serializable {

	private UsuarioRolId id;
	private Rol rol;
	private Usuario usuario;

	public UsuarioRol() {
	}

	public UsuarioRol(UsuarioRolId id, Rol rol, Usuario usuario) {
		this.id = id;
		this.rol = rol;
		this.usuario = usuario;
	}

	public UsuarioRolId getId() {
		return this.id;
	}

	public void setId(UsuarioRolId id) {
		this.id = id;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
