package com.solmit.entidad;
// Generated 25/05/2017 05:38:09 PM by Hibernate Tools 5.2.3.Final

/**
 * UsuarioRolId generated by hbm2java
 */
public class UsuarioRolId implements java.io.Serializable {

	private String rolNombre;
	private String idUsuario;

	public UsuarioRolId() {
	}

	public UsuarioRolId(String rolNombre, String idUsuario) {
		this.rolNombre = rolNombre;
		this.idUsuario = idUsuario;
	}

	public String getRolNombre() {
		return this.rolNombre;
	}

	public void setRolNombre(String rolNombre) {
		this.rolNombre = rolNombre;
	}

	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioRolId))
			return false;
		UsuarioRolId castOther = (UsuarioRolId) other;

		return ((this.getRolNombre() == castOther.getRolNombre()) || (this.getRolNombre() != null
				&& castOther.getRolNombre() != null && this.getRolNombre().equals(castOther.getRolNombre())))
				&& ((this.getIdUsuario() == castOther.getIdUsuario()) || (this.getIdUsuario() != null
						&& castOther.getIdUsuario() != null && this.getIdUsuario().equals(castOther.getIdUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRolNombre() == null ? 0 : this.getRolNombre().hashCode());
		result = 37 * result + (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		return result;
	}

}
